name: "Manual | Build Container Image"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from"
        required: true
        default: "main"
      tag:
        description: "Tag for the image (only one supported)"
        required: true
        default: "dev-latest"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and Push Container Image to GitHub Container Registry
    runs-on: self-hosted

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - name: downcase REGISTRY
        run: |
          echo "REGISTRY_L=${REGISTRY@L}" >> "${GITHUB_ENV}"
      - name: downcase IMAGE_NAME
        run: |
          echo "IMAGE_NAME_L=${IMAGE_NAME@L}" >> "${GITHUB_ENV}"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # Uses the `docker/setup-buildx-action` action to set up the Docker Buildx builder instance.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: "Authenticate with GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: "Set Container Image Metadata"
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag }}

      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: "Build and Push Container Image"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY_L }}/${{ env.IMAGE_NAME_L }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY_L }}/${{ env.IMAGE_NAME_L }}:cache,mode=max
